// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseCheckbox: typeof import('./components/BaseCheckbox.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    BaseSelect: typeof import('./components/BaseSelect.vue')['default']
    BaseTextarea: typeof import('./components/BaseTextarea.vue')['default']
    Readme: typeof import('./components/Readme.md')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
