// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseCheckbox: typeof import('./components/BaseCheckbox.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    BaseNotification: typeof import('./components/BaseNotification.vue')['default']
    BaseSelect: typeof import('./components/BaseSelect.vue')['default']
    BaseTextarea: typeof import('./components/BaseTextarea.vue')['default']
    ErrorAlert: typeof import('./components/ErrorAlert.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Home: typeof import('./components/Home.md')['default']
    ModalWrongNetwork: typeof import('./components/ModalWrongNetwork.vue')['default']
    Readme: typeof import('./components/Readme.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableAssets: typeof import('./components/TableAssets.vue')['default']
    TokenImage: typeof import('./components/TokenImage.vue')['default']
  }
}
